# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(907, 518)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        mainWindow.setFont(font)
        mainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftMenuContainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.LeftMenuContainer.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.LeftMenuContainer.setFont(font)
        self.LeftMenuContainer.setStyleSheet("#LeftMenuContainer{\n"
"    background-color: #A2D9CE;\n"
"}\n"
"QPushButton {\n"
"    padding:10px;\n"
"}")
        self.LeftMenuContainer.setObjectName("LeftMenuContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LeftMenuContainer)
        self.verticalLayout.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.LeftMenuContainer)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.frame.setFont(font)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background:transparent;\n"
"padding-top:15px;")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logos/logo_0.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(130, 40))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("#frame_2 QPushButton{\n"
"    padding:15px;\n"
"    height:25px;\n"
"    font-family:\"Montserrat\";\n"
"    font-size:16px;\n"
"    border-radius:8px;\n"
"    background-color:#16A085;\n"
"}\n"
"#frame_2 QPushButton::hover{\n"
"    background-color: #ffffff;\n"
"}\n"
"#frame_2 {\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_2.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/logos/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/logos/student.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/logos/employee.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/logos/hostel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(36, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.verticalLayout_3.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.LeftMenuContainer)
        self.MainContainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.MainContainer.setStyleSheet("")
        self.MainContainer.setObjectName("MainContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Header = QtWidgets.QWidget(parent=self.MainContainer)
        self.Header.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Header.setStyleSheet("#Header{\n"
"    background-color:#A3E4D7 ;\n"
"}")
        self.Header.setObjectName("Header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_8 = QtWidgets.QFrame(parent=self.Header)
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setContentsMargins(-1, 7, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #0E6655;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(parent=self.Header)
        self.frame_9.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_9.setStyleSheet("#frame_9 QPushButton{\n"
"    padding:15px;\n"
"    height:20px;\n"
"    font-family:\"Montserrat\";\n"
"    font-size:16px;\n"
"    border-radius:9px;\n"
"    background-color:#138D75;\n"
"    color:white;\n"
"}\n"
"\n"
"#frame_9 QPushButton::hover{\n"
"    background-color: #E8F8F5;\n"
"    color:black;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton_21 = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushButton_21.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/logos/logout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_21.setIcon(icon5)
        self.pushButton_21.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_3.addWidget(self.pushButton_21)
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.Header)
        self.Body = QtWidgets.QWidget(parent=self.MainContainer)
        self.Body.setStyleSheet("background:solid;\n"
"border-top-left-radius:25px;\n"
"\n"
"")
        self.Body.setObjectName("Body")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.Body)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("\n"
"#stackedWidget {\n"
"font: 11pt \"Montserrat\";\n"
"}\n"
"\n"
"#stackedWidget{\n"
"font: 11pt \"Montserrat\";\n"
"}\n"
"\n"
"#stackedWidget QTabBar::tab{\n"
"    font: 12pt \"Montserrat\";\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.employees = QtWidgets.QWidget()
        self.employees.setObjectName("employees")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.employees)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tabWidget_3 = QtWidgets.QTabWidget(parent=self.employees)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setStyleSheet("QTabBar::tab{\n"
"    background-color: #45B39D;\n"
"      padding: 10px;\n"
"     margin-right:5px;\n"
"    border: 1px solid lightgray;\n"
"     /*border-top-left-radius: 15px;*/\n"
"} \n"
"QTabBar::tab:selected { \n"
"     background:rgb(226, 226, 226); /*rgb(245, 245, 245)*/; \n"
"      margin-bottom: -1px; \n"
"}\n"
"QTabWidget::pane {\n"
"     border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"     top:-1px; \n"
"} \n"
"")
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_7 = QtWidgets.QFrame(parent=self.tab_7)
        self.frame_7.setStyleSheet("\n"
"#frame_7 QLabel,QLineEdit,QComboBox,QDateEdit,QPushButton,QRadioButton{\n"
"    font: 10pt \"Montserrat\";\n"
"}\n"
"#frame_7 QLineEdit {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"#frame_7 QDateEdit,QTextEdit,QComboBox {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"#frame_7 QPushButton{\n"
"    background-color:rgb(177, 177, 177);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 141, 41))
        self.label_6.setObjectName("label_6")
        self.label_21 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_21.setGeometry(QtCore.QRect(410, 10, 71, 41))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_22.setGeometry(QtCore.QRect(20, 110, 141, 31))
        self.label_22.setObjectName("label_22")
        self.EmployeeIDText = QtWidgets.QLineEdit(parent=self.frame_7)
        self.EmployeeIDText.setGeometry(QtCore.QRect(180, 10, 221, 41))
        self.EmployeeIDText.setText("")
        self.EmployeeIDText.setObjectName("EmployeeIDText")
        self.label_23 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_23.setGeometry(QtCore.QRect(20, 200, 141, 41))
        self.label_23.setObjectName("label_23")
        self.SaveEmployeeButton = QtWidgets.QPushButton(parent=self.frame_7)
        self.SaveEmployeeButton.setGeometry(QtCore.QRect(410, 200, 241, 41))
        self.SaveEmployeeButton.setObjectName("SaveEmployeeButton")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 141, 41))
        self.label_10.setObjectName("label_10")
        self.EmployeeNameText = QtWidgets.QLineEdit(parent=self.frame_7)
        self.EmployeeNameText.setGeometry(QtCore.QRect(180, 60, 471, 41))
        self.EmployeeNameText.setText("")
        self.EmployeeNameText.setObjectName("EmployeeNameText")
        self.EmployeeAddress = QtWidgets.QTextEdit(parent=self.frame_7)
        self.EmployeeAddress.setGeometry(QtCore.QRect(180, 110, 471, 81))
        self.EmployeeAddress.setObjectName("EmployeeAddress")
        self.EmployeeCategoryCombo = QtWidgets.QComboBox(parent=self.frame_7)
        self.EmployeeCategoryCombo.setGeometry(QtCore.QRect(480, 10, 171, 41))
        self.EmployeeCategoryCombo.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Afar, QtCore.QLocale.Country.Ethiopia))
        self.EmployeeCategoryCombo.setObjectName("EmployeeCategoryCombo")
        self.EmployeeCategoryCombo.addItem("")
        self.EmployeeCategoryCombo.addItem("")
        self.EmployeeCategoryCombo.addItem("")
        self.EmployeeTelephoneText = QtWidgets.QLineEdit(parent=self.frame_7)
        self.EmployeeTelephoneText.setGeometry(QtCore.QRect(180, 200, 221, 41))
        self.EmployeeTelephoneText.setText("")
        self.EmployeeTelephoneText.setObjectName("EmployeeTelephoneText")
        self.verticalLayout_11.addWidget(self.frame_7)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_10 = QtWidgets.QFrame(parent=self.tab_8)
        self.frame_10.setStyleSheet("\n"
"#frame_10 QLabel,QLineEdit,QComboBox,QDateEdit,QPushButton,QRadioButton{\n"
"    font: 10pt \"Montserrat\";\n"
"}\n"
"#frame_10 QLineEdit {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"#frame_10 QDateEdit,QTextEdit,QComboBox {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"#frame_10 QPushButton{\n"
"    background-color:rgb(177, 177, 177);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 141, 41))
        self.label_11.setObjectName("label_11")
        self.EmployeeIDText_2 = QtWidgets.QLineEdit(parent=self.frame_10)
        self.EmployeeIDText_2.setGeometry(QtCore.QRect(180, 10, 221, 41))
        self.EmployeeIDText_2.setStyleSheet("")
        self.EmployeeIDText_2.setText("")
        self.EmployeeIDText_2.setObjectName("EmployeeIDText_2")
        self.SearchEmployeeButton = QtWidgets.QPushButton(parent=self.frame_10)
        self.SearchEmployeeButton.setGeometry(QtCore.QRect(410, 10, 241, 41))
        self.SearchEmployeeButton.setObjectName("SearchEmployeeButton")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.frame_10)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 60, 651, 171))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.SameAssignmentButton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.SameAssignmentButton.setGeometry(QtCore.QRect(170, 110, 301, 51))
        self.SameAssignmentButton.setObjectName("SameAssignmentButton")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 141, 41))
        self.label_12.setObjectName("label_12")
        self.label_24 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(10, 60, 121, 41))
        self.label_24.setObjectName("label_24")
        self.EmployeeNameText_2 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.EmployeeNameText_2.setGeometry(QtCore.QRect(170, 10, 471, 41))
        self.EmployeeNameText_2.setText("")
        self.EmployeeNameText_2.setObjectName("EmployeeNameText_2")
        self.EmployeeHostelCombo = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.EmployeeHostelCombo.setEnabled(False)
        self.EmployeeHostelCombo.setGeometry(QtCore.QRect(170, 60, 301, 41))
        self.EmployeeHostelCombo.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Afar, QtCore.QLocale.Country.Ethiopia))
        self.EmployeeHostelCombo.setObjectName("EmployeeHostelCombo")
        self.ChangeHostelButton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.ChangeHostelButton.setGeometry(QtCore.QRect(490, 60, 41, 41))
        self.ChangeHostelButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/logos/change.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ChangeHostelButton.setIcon(icon6)
        self.ChangeHostelButton.setIconSize(QtCore.QSize(30, 30))
        self.ChangeHostelButton.setObjectName("ChangeHostelButton")
        self.verticalLayout_12.addWidget(self.frame_10)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_11 = QtWidgets.QFrame(parent=self.tab_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.EmployeeTable = QtWidgets.QTableWidget(parent=self.frame_11)
        self.EmployeeTable.setGeometry(QtCore.QRect(10, 10, 651, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmployeeTable.sizePolicy().hasHeightForWidth())
        self.EmployeeTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.EmployeeTable.setFont(font)
        self.EmployeeTable.setAutoFillBackground(True)
        self.EmployeeTable.setStyleSheet("font: 10pt \"Montserrat\";\n"
"background-color:lightgray;")
        self.EmployeeTable.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.EmployeeTable.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.EmployeeTable.setCornerButtonEnabled(True)
        self.EmployeeTable.setObjectName("EmployeeTable")
        self.EmployeeTable.setColumnCount(4)
        self.EmployeeTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.EmployeeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EmployeeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EmployeeTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EmployeeTable.setHorizontalHeaderItem(3, item)
        self.EmployeeTable.horizontalHeader().setDefaultSectionSize(118)
        self.EmployeeTable.horizontalHeader().setStretchLastSection(True)
        self.EmployeeTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_13.addWidget(self.frame_11)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.horizontalLayout_9.addWidget(self.tabWidget_3)
        self.stackedWidget.addWidget(self.employees)
        self.students = QtWidgets.QWidget()
        self.students.setStyleSheet("QTabBar::tab{\n"
"font: 12pt \"Montserrat\";\n"
"}")
        self.students.setObjectName("students")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.students)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.students)
        self.tabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar::tab{\n"
"    background-color: #45B39D;\n"
"      padding: 10px;\n"
"     margin-right:5px;\n"
"    border: 1px solid lightgray;\n"
"     /*border-top-left-radius: 15px;*/\n"
"} \n"
"QTabBar::tab:selected { \n"
"     background:rgb(226, 226, 226); /*rgb(245, 245, 245)*/; \n"
"      margin-bottom: -1px; \n"
"}\n"
"QTabWidget::pane {\n"
"     border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"     top:-1px; \n"
"} \n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_4 = QtWidgets.QFrame(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("\n"
"#frame_4 QLabel,QLineEdit,QComboBox,QDateEdit,QPushButton,QRadioButton{\n"
"    font: 10pt \"Montserrat\";\n"
"}\n"
"#frame_4 QLineEdit {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"#frame_4 QDateEdit,QTextEdit,QComboBox {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"#frame_4 QPushButton{\n"
"    background-color:rgb(177, 177, 177);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(410, 10, 111, 41))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 141, 41))
        self.label_3.setObjectName("label_3")
        self.StudentNameText_2 = QtWidgets.QLineEdit(parent=self.frame_4)
        self.StudentNameText_2.setGeometry(QtCore.QRect(170, 160, 471, 41))
        self.StudentNameText_2.setObjectName("StudentNameText_2")
        self.StudentIDText_2 = QtWidgets.QLineEdit(parent=self.frame_4)
        self.StudentIDText_2.setGeometry(QtCore.QRect(170, 10, 221, 41))
        self.StudentIDText_2.setObjectName("StudentIDText_2")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 141, 41))
        self.label_7.setObjectName("label_7")
        self.AdmissionDateCalander = QtWidgets.QDateEdit(parent=self.frame_4)
        self.AdmissionDateCalander.setGeometry(QtCore.QRect(530, 10, 111, 41))
        self.AdmissionDateCalander.setCalendarPopup(True)
        self.AdmissionDateCalander.setObjectName("AdmissionDateCalander")
        self.AddressText_2 = QtWidgets.QTextEdit(parent=self.frame_4)
        self.AddressText_2.setGeometry(QtCore.QRect(170, 210, 471, 81))
        self.AddressText_2.setObjectName("AddressText_2")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(10, 210, 141, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(10, 60, 151, 41))
        self.label_16.setObjectName("label_16")
        self.TelephoneNoText = QtWidgets.QLineEdit(parent=self.frame_4)
        self.TelephoneNoText.setGeometry(QtCore.QRect(170, 300, 221, 41))
        self.TelephoneNoText.setObjectName("TelephoneNoText")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(10, 300, 141, 41))
        self.label_18.setObjectName("label_18")
        self.SaveStudentButton = QtWidgets.QPushButton(parent=self.frame_4)
        self.SaveStudentButton.setGeometry(QtCore.QRect(400, 300, 241, 41))
        self.SaveStudentButton.setObjectName("SaveStudentButton")
        self.FacultyCombo = QtWidgets.QComboBox(parent=self.frame_4)
        self.FacultyCombo.setGeometry(QtCore.QRect(170, 60, 221, 41))
        self.FacultyCombo.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Afar, QtCore.QLocale.Country.Ethiopia))
        self.FacultyCombo.setObjectName("FacultyCombo")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(410, 110, 111, 41))
        self.label_13.setObjectName("label_13")
        self.RoomIDText_2 = QtWidgets.QLineEdit(parent=self.frame_4)
        self.RoomIDText_2.setGeometry(QtCore.QRect(530, 110, 111, 41))
        self.RoomIDText_2.setObjectName("RoomIDText_2")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(10, 110, 141, 41))
        self.label_14.setObjectName("label_14")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(410, 60, 101, 41))
        self.label_17.setObjectName("label_17")
        self.BatchCombo = QtWidgets.QComboBox(parent=self.frame_4)
        self.BatchCombo.setGeometry(QtCore.QRect(530, 60, 111, 41))
        self.BatchCombo.setObjectName("BatchCombo")
        self.HostelCombo = QtWidgets.QComboBox(parent=self.frame_4)
        self.HostelCombo.setGeometry(QtCore.QRect(170, 110, 221, 41))
        self.HostelCombo.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Afar, QtCore.QLocale.Country.Ethiopia))
        self.HostelCombo.setObjectName("HostelCombo")
        self.verticalLayout_8.addWidget(self.frame_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_13 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_13.setStyleSheet("\n"
"#frame_13 QLabel,QLineEdit,QComboBox,QDateEdit,QPushButton,QRadioButton{\n"
"    font: 10pt \"Montserrat\";\n"
"}\n"
"#frame_13 QLineEdit {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"#frame_13 QDateEdit,QTextEdit,QComboBox {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"#frame_13 QPushButton{\n"
"    background-color:rgb(177, 177, 177);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.StudentIDCombo = QtWidgets.QComboBox(parent=self.frame_13)
        self.StudentIDCombo.setGeometry(QtCore.QRect(180, 10, 201, 41))
        self.StudentIDCombo.setEditable(True)
        self.StudentIDCombo.setObjectName("StudentIDCombo")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_19.setGeometry(QtCore.QRect(20, 10, 141, 41))
        self.label_19.setObjectName("label_19")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.frame_13)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 60, 651, 301))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_20 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 141, 41))
        self.label_20.setObjectName("label_20")
        self.RoomIDText_3 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.RoomIDText_3.setGeometry(QtCore.QRect(530, 110, 111, 41))
        self.RoomIDText_3.setObjectName("RoomIDText_3")
        self.label_25 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(10, 160, 141, 31))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(420, 60, 101, 41))
        self.label_26.setObjectName("label_26")
        self.BatchNoText_2 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.BatchNoText_2.setGeometry(QtCore.QRect(530, 60, 111, 41))
        self.BatchNoText_2.setObjectName("BatchNoText_2")
        self.label_27 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(420, 250, 111, 41))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(420, 110, 91, 41))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(10, 110, 141, 41))
        self.label_29.setObjectName("label_29")
        self.TelephoneNoText_2 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.TelephoneNoText_2.setGeometry(QtCore.QRect(170, 250, 221, 41))
        self.TelephoneNoText_2.setObjectName("TelephoneNoText_2")
        self.AddressText = QtWidgets.QTextEdit(parent=self.groupBox_3)
        self.AddressText.setGeometry(QtCore.QRect(170, 160, 471, 81))
        self.AddressText.setObjectName("AddressText")
        self.label_30 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_30.setGeometry(QtCore.QRect(10, 60, 151, 41))
        self.label_30.setObjectName("label_30")
        self.HostelNameText_4 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.HostelNameText_4.setGeometry(QtCore.QRect(170, 110, 221, 41))
        self.HostelNameText_4.setText("")
        self.HostelNameText_4.setObjectName("HostelNameText_4")
        self.StudentNameText_3 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.StudentNameText_3.setGeometry(QtCore.QRect(170, 10, 471, 41))
        self.StudentNameText_3.setObjectName("StudentNameText_3")
        self.label_31 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(10, 250, 141, 41))
        self.label_31.setObjectName("label_31")
        self.FacultyText = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.FacultyText.setGeometry(QtCore.QRect(170, 60, 221, 41))
        self.FacultyText.setText("")
        self.FacultyText.setObjectName("FacultyText")
        self.AdmissionDateText = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.AdmissionDateText.setGeometry(QtCore.QRect(530, 250, 111, 41))
        self.AdmissionDateText.setObjectName("AdmissionDateText")
        self.SearcStudentButton = QtWidgets.QPushButton(parent=self.frame_13)
        self.SearcStudentButton.setGeometry(QtCore.QRect(390, 10, 261, 41))
        self.SearcStudentButton.setObjectName("SearcStudentButton")
        self.horizontalLayout_7.addWidget(self.frame_13)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_15 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.StudentTable = QtWidgets.QTableWidget(parent=self.frame_15)
        self.StudentTable.setGeometry(QtCore.QRect(10, 10, 651, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StudentTable.sizePolicy().hasHeightForWidth())
        self.StudentTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.StudentTable.setFont(font)
        self.StudentTable.setAutoFillBackground(True)
        self.StudentTable.setStyleSheet("font: 10pt \"Montserrat\";\n"
"background-color:lightgray;")
        self.StudentTable.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.StudentTable.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.StudentTable.setCornerButtonEnabled(True)
        self.StudentTable.setObjectName("StudentTable")
        self.StudentTable.setColumnCount(5)
        self.StudentTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.StudentTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentTable.setHorizontalHeaderItem(4, item)
        self.StudentTable.horizontalHeader().setDefaultSectionSize(118)
        self.StudentTable.horizontalHeader().setStretchLastSection(True)
        self.StudentTable.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_12.addWidget(self.frame_15)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.students)
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.home)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_16 = QtWidgets.QFrame(parent=self.home)
        self.frame_16.setStyleSheet("\n"
"#frame_16{\n"
"/*background-color: rgb(255, 241, 188);*/\n"
"}\n"
"#frame_16 QLabel,QLineEdit,QComboBox,QDateEdit,QPushButton,QRadioButton{\n"
"    font: \"Montserrat\";\n"
"}\n"
"#frame_16 QLineEdit {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"#frame_16 QDateEdit,QTextEdit,QComboBox {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"#frame_16 QPushButton{\n"
"    background-color:rgb(177, 177, 177);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"QGroupBox{\n"
"    border: 3px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"#frame_16 QLabel{\n"
"    border-radius:0px;\n"
"    background:none;;\n"
"}\n"
"")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.TodayDateLabel = QtWidgets.QLabel(parent=self.frame_16)
        self.TodayDateLabel.setGeometry(QtCore.QRect(410, 60, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TodayDateLabel.setFont(font)
        self.TodayDateLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.TodayDateLabel.setStyleSheet("background-color:#73C6B6 ;")
        self.TodayDateLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TodayDateLabel.setObjectName("TodayDateLabel")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.frame_16)
        self.calendarWidget.setGeometry(QtCore.QRect(410, 110, 271, 191))
        self.calendarWidget.setStyleSheet("color:balck;\n"
"font-family:\"Montserrat\";\n"
"font-size:12px;")
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.HorizontalHeaderFormat.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.ISOWeekNumbers)
        self.calendarWidget.setObjectName("calendarWidget")
        self.TodayTimeLCD = QtWidgets.QLCDNumber(parent=self.frame_16)
        self.TodayTimeLCD.setGeometry(QtCore.QRect(410, 0, 271, 51))
        self.TodayTimeLCD.setStyleSheet("background-color:#A2D9CE;\n"
"border-radius:0px;")
        self.TodayTimeLCD.setObjectName("TodayTimeLCD")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_16)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:#73C6B6;\n"
"font-family:\"Montserrat\";\n"
"color:white;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame_16)
        self.groupBox.setGeometry(QtCore.QRect(0, 60, 401, 241))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("font-family:\"Montserrat\";")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.StudentIDText = QtWidgets.QLineEdit(parent=self.groupBox)
        self.StudentIDText.setGeometry(QtCore.QRect(180, 10, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.StudentIDText.setFont(font)
        self.StudentIDText.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.StudentIDText.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.StudentIDText.setClearButtonEnabled(True)
        self.StudentIDText.setObjectName("StudentIDText")
        self.StudentNameText = QtWidgets.QLineEdit(parent=self.groupBox)
        self.StudentNameText.setEnabled(False)
        self.StudentNameText.setGeometry(QtCore.QRect(10, 70, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.StudentNameText.setFont(font)
        self.StudentNameText.setObjectName("StudentNameText")
        self.EntranceStatus = QtWidgets.QLineEdit(parent=self.groupBox)
        self.EntranceStatus.setEnabled(False)
        self.EntranceStatus.setGeometry(QtCore.QRect(70, 130, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(70)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.EntranceStatus.setFont(font)
        self.EntranceStatus.setStyleSheet("background-color:none;\n"
"border:1px solid #117A65;")
        self.EntranceStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.EntranceStatus.setObjectName("EntranceStatus")
        self.horizontalLayout_13.addWidget(self.frame_16)
        self.stackedWidget.addWidget(self.home)
        self.Hostels = QtWidgets.QWidget()
        self.Hostels.setObjectName("Hostels")
        self.tabWidget_4 = QtWidgets.QTabWidget(parent=self.Hostels)
        self.tabWidget_4.setEnabled(True)
        self.tabWidget_4.setGeometry(QtCore.QRect(10, 10, 691, 431))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.tabWidget_4.setFont(font)
        self.tabWidget_4.setStyleSheet("QTabBar::tab{\n"
"    background-color: #45B39D;\n"
"      padding: 10px;\n"
"     margin-right:5px;\n"
"    border: 1px solid lightgray;\n"
"     /*border-top-left-radius: 15px;*/\n"
"} \n"
"QTabBar::tab:selected { \n"
"     background:rgb(226, 226, 226); /*rgb(245, 245, 245)*/; \n"
"      margin-bottom: -1px; \n"
"}\n"
"QTabWidget::pane {\n"
"     border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"     top:-1px; \n"
"} \n"
"")
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_12 = QtWidgets.QFrame(parent=self.tab_10)
        self.frame_12.setStyleSheet("\n"
"#frame_7 QLabel,QLineEdit,QComboBox,QDateEdit,QPushButton,QRadioButton{\n"
"    font: 10pt \"Montserrat\";\n"
"}\n"
"#frame_7 QLineEdit {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"#frame_7 QDateEdit,QTextEdit,QComboBox {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"#frame_7 QPushButton{\n"
"    background-color:rgb(177, 177, 177);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.HostelTable = QtWidgets.QTableWidget(parent=self.frame_12)
        self.HostelTable.setGeometry(QtCore.QRect(10, 10, 651, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HostelTable.sizePolicy().hasHeightForWidth())
        self.HostelTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.HostelTable.setFont(font)
        self.HostelTable.setAutoFillBackground(True)
        self.HostelTable.setStyleSheet("font: 10pt \"Montserrat\";\n"
"background-color:lightgray;")
        self.HostelTable.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.HostelTable.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.HostelTable.setCornerButtonEnabled(True)
        self.HostelTable.setObjectName("HostelTable")
        self.HostelTable.setColumnCount(4)
        self.HostelTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.HostelTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HostelTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HostelTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.HostelTable.setHorizontalHeaderItem(3, item)
        self.HostelTable.horizontalHeader().setDefaultSectionSize(118)
        self.HostelTable.horizontalHeader().setStretchLastSection(True)
        self.HostelTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_14.addWidget(self.frame_12)
        self.tabWidget_4.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_11)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_14 = QtWidgets.QFrame(parent=self.tab_11)
        self.frame_14.setStyleSheet("#frame_14 QLabel,QLineEdit,QComboBox,QDateEdit,QPushButton,QRadioButton{\n"
"    font: 10pt \"Montserrat\";\n"
"}\n"
"\n"
"#frame_14 QPushButton{\n"
"    background-color:rgb(177, 177, 177);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"\n"
"#frame_14 QDateEdit,QTextEdit,QComboBox {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"QGroupBox{\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"    font: 10pt \"Montserrat\";\n"
"}\n"
"\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.RoomTable = QtWidgets.QTableWidget(parent=self.frame_14)
        self.RoomTable.setGeometry(QtCore.QRect(400, 60, 251, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RoomTable.sizePolicy().hasHeightForWidth())
        self.RoomTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.RoomTable.setFont(font)
        self.RoomTable.setAutoFillBackground(True)
        self.RoomTable.setStyleSheet("font: 10pt \"Montserrat\";\n"
"background-color:lightgray;")
        self.RoomTable.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.RoomTable.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.RoomTable.setCornerButtonEnabled(True)
        self.RoomTable.setObjectName("RoomTable")
        self.RoomTable.setColumnCount(2)
        self.RoomTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.RoomTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RoomTable.setHorizontalHeaderItem(1, item)
        self.RoomTable.horizontalHeader().setDefaultSectionSize(118)
        self.RoomTable.horizontalHeader().setStretchLastSection(True)
        self.RoomTable.verticalHeader().setStretchLastSection(False)
        self.SearchHostelButton = QtWidgets.QPushButton(parent=self.frame_14)
        self.SearchHostelButton.setGeometry(QtCore.QRect(400, 10, 121, 41))
        self.SearchHostelButton.setObjectName("SearchHostelButton")
        self.label_32 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_32.setGeometry(QtCore.QRect(120, 10, 51, 41))
        self.label_32.setObjectName("label_32")
        self.SelectHostelCombo = QtWidgets.QComboBox(parent=self.frame_14)
        self.SelectHostelCombo.setGeometry(QtCore.QRect(180, 10, 201, 41))
        self.SelectHostelCombo.setEditable(True)
        self.SelectHostelCombo.setObjectName("SelectHostelCombo")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.frame_14)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 60, 361, 141))
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 101, 41))
        self.label_9.setObjectName("label_9")
        self.HostelNameText = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.HostelNameText.setGeometry(QtCore.QRect(120, 30, 231, 41))
        self.HostelNameText.setStyleSheet("border-radius:0px;\n"
"background-color:rgb(230, 230, 230);\n"
"border: 1px solid lightgray;")
        self.HostelNameText.setObjectName("HostelNameText")
        self.label_34 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(10, 30, 101, 41))
        self.label_34.setObjectName("label_34")
        self.HostelLoctionText = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.HostelLoctionText.setGeometry(QtCore.QRect(120, 80, 231, 41))
        self.HostelLoctionText.setStyleSheet("border-radius:0px;\n"
"background-color:rgb(230, 230, 230);\n"
"border: 1px solid lightgray;")
        self.HostelLoctionText.setText("")
        self.HostelLoctionText.setObjectName("HostelLoctionText")
        self.verticalLayout_15.addWidget(self.frame_14)
        self.tabWidget_4.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_12)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_17 = QtWidgets.QFrame(parent=self.tab_12)
        self.frame_17.setStyleSheet("#frame_17 QLabel,QLineEdit,QComboBox,QDateEdit,QPushButton,QRadioButton{\n"
"    font: 10pt \"Montserrat\";\n"
"}\n"
"\n"
"#frame_17 QPushButton{\n"
"    background-color:rgb(177, 177, 177);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"\n"
"#frame_17 QDateEdit,QTextEdit,QComboBox {\n"
"    background-color:rgb(230, 230, 230);\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"QGroupBox{\n"
"    border: 1px solid lightgray;\n"
"    border-radius:0px;\n"
"    font: 10pt \"Montserrat\";\n"
"}\n"
"\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_35 = QtWidgets.QLabel(parent=self.frame_17)
        self.label_35.setGeometry(QtCore.QRect(10, 10, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color:#73C6B6;\n"
"font-family:\"Montserrat\";\n"
"color:white;\n"
"border-radius:0px;")
        self.label_35.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.frame_17)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 60, 651, 91))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.HostelNameText_2 = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.HostelNameText_2.setGeometry(QtCore.QRect(130, 30, 231, 41))
        self.HostelNameText_2.setStyleSheet("border-radius:0px;\n"
"background-color:rgb(230, 230, 230);\n"
"border: 1px solid lightgray;")
        self.HostelNameText_2.setObjectName("HostelNameText_2")
        self.HostelIDText = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.HostelIDText.setGeometry(QtCore.QRect(10, 30, 101, 41))
        self.HostelIDText.setStyleSheet("border-radius:0px;\n"
"background-color:rgb(230, 230, 230);\n"
"border: 1px solid lightgray;")
        self.HostelIDText.setReadOnly(True)
        self.HostelIDText.setObjectName("HostelIDText")
        self.label_38 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_38.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_38.setObjectName("label_38")
        self.label_37 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_37.setGeometry(QtCore.QRect(130, 10, 51, 21))
        self.label_37.setObjectName("label_37")
        self.AddHostelButton = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.AddHostelButton.setGeometry(QtCore.QRect(560, 30, 81, 41))
        self.AddHostelButton.setObjectName("AddHostelButton")
        self.label_36 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_36.setGeometry(QtCore.QRect(380, 10, 71, 21))
        self.label_36.setObjectName("label_36")
        self.HostelLocationText = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.HostelLocationText.setGeometry(QtCore.QRect(380, 30, 171, 41))
        self.HostelLocationText.setStyleSheet("border-radius:0px;\n"
"background-color:rgb(230, 230, 230);\n"
"border: 1px solid lightgray;")
        self.HostelLocationText.setText("")
        self.HostelLocationText.setObjectName("HostelLocationText")
        self.label_42 = QtWidgets.QLabel(parent=self.frame_17)
        self.label_42.setGeometry(QtCore.QRect(10, 170, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background-color:#73C6B6;\n"
"font-family:\"Montserrat\";\n"
"color:white;\n"
"border-radius:0px;")
        self.label_42.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.frame_17)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 220, 651, 91))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.RoomIDText = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.RoomIDText.setGeometry(QtCore.QRect(170, 30, 191, 41))
        self.RoomIDText.setStyleSheet("border-radius:0px;\n"
"background-color:rgb(230, 230, 230);\n"
"border: 1px solid lightgray;")
        self.RoomIDText.setObjectName("RoomIDText")
        self.label_39 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_39.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_40.setGeometry(QtCore.QRect(170, 10, 61, 21))
        self.label_40.setObjectName("label_40")
        self.AddRoomButton = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.AddRoomButton.setGeometry(QtCore.QRect(560, 30, 81, 41))
        self.AddRoomButton.setObjectName("AddRoomButton")
        self.label_41 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_41.setGeometry(QtCore.QRect(380, 10, 71, 21))
        self.label_41.setObjectName("label_41")
        self.RoomCapacityText = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.RoomCapacityText.setGeometry(QtCore.QRect(380, 30, 171, 41))
        self.RoomCapacityText.setStyleSheet("border-radius:0px;\n"
"background-color:rgb(230, 230, 230);\n"
"border: 1px solid lightgray;")
        self.RoomCapacityText.setText("")
        self.RoomCapacityText.setObjectName("RoomCapacityText")
        self.HostelIDCombo = QtWidgets.QComboBox(parent=self.groupBox_6)
        self.HostelIDCombo.setGeometry(QtCore.QRect(10, 30, 141, 41))
        self.HostelIDCombo.setObjectName("HostelIDCombo")
        self.verticalLayout_16.addWidget(self.frame_17)
        self.tabWidget_4.addTab(self.tab_12, "")
        self.stackedWidget.addWidget(self.Hostels)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.Body)
        self.horizontalLayout.addWidget(self.MainContainer)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_4.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.StudentIDText, self.EntranceStatus)
        mainWindow.setTabOrder(self.EntranceStatus, self.StudentIDText_2)
        mainWindow.setTabOrder(self.StudentIDText_2, self.AdmissionDateCalander)
        mainWindow.setTabOrder(self.AdmissionDateCalander, self.FacultyCombo)
        mainWindow.setTabOrder(self.FacultyCombo, self.RoomIDText_2)
        mainWindow.setTabOrder(self.RoomIDText_2, self.StudentNameText_2)
        mainWindow.setTabOrder(self.StudentNameText_2, self.AddressText_2)
        mainWindow.setTabOrder(self.AddressText_2, self.TelephoneNoText)
        mainWindow.setTabOrder(self.TelephoneNoText, self.SaveStudentButton)
        mainWindow.setTabOrder(self.SaveStudentButton, self.StudentIDCombo)
        mainWindow.setTabOrder(self.StudentIDCombo, self.SearcStudentButton)
        mainWindow.setTabOrder(self.SearcStudentButton, self.StudentNameText_3)
        mainWindow.setTabOrder(self.StudentNameText_3, self.FacultyText)
        mainWindow.setTabOrder(self.FacultyText, self.HostelNameText_4)
        mainWindow.setTabOrder(self.HostelNameText_4, self.BatchNoText_2)
        mainWindow.setTabOrder(self.BatchNoText_2, self.RoomIDText_3)
        mainWindow.setTabOrder(self.RoomIDText_3, self.AddressText)
        mainWindow.setTabOrder(self.AddressText, self.TelephoneNoText_2)
        mainWindow.setTabOrder(self.TelephoneNoText_2, self.AdmissionDateText)
        mainWindow.setTabOrder(self.AdmissionDateText, self.StudentTable)
        mainWindow.setTabOrder(self.StudentTable, self.EmployeeIDText)
        mainWindow.setTabOrder(self.EmployeeIDText, self.EmployeeCategoryCombo)
        mainWindow.setTabOrder(self.EmployeeCategoryCombo, self.EmployeeNameText)
        mainWindow.setTabOrder(self.EmployeeNameText, self.EmployeeAddress)
        mainWindow.setTabOrder(self.EmployeeAddress, self.EmployeeTelephoneText)
        mainWindow.setTabOrder(self.EmployeeTelephoneText, self.SaveEmployeeButton)
        mainWindow.setTabOrder(self.SaveEmployeeButton, self.EmployeeIDText_2)
        mainWindow.setTabOrder(self.EmployeeIDText_2, self.SearchEmployeeButton)
        mainWindow.setTabOrder(self.SearchEmployeeButton, self.EmployeeNameText_2)
        mainWindow.setTabOrder(self.EmployeeNameText_2, self.EmployeeHostelCombo)
        mainWindow.setTabOrder(self.EmployeeHostelCombo, self.ChangeHostelButton)
        mainWindow.setTabOrder(self.ChangeHostelButton, self.SameAssignmentButton)
        mainWindow.setTabOrder(self.SameAssignmentButton, self.EmployeeTable)
        mainWindow.setTabOrder(self.EmployeeTable, self.HostelTable)
        mainWindow.setTabOrder(self.HostelTable, self.SelectHostelCombo)
        mainWindow.setTabOrder(self.SelectHostelCombo, self.SearchHostelButton)
        mainWindow.setTabOrder(self.SearchHostelButton, self.HostelNameText)
        mainWindow.setTabOrder(self.HostelNameText, self.HostelLoctionText)
        mainWindow.setTabOrder(self.HostelLoctionText, self.RoomTable)
        mainWindow.setTabOrder(self.RoomTable, self.HostelIDText)
        mainWindow.setTabOrder(self.HostelIDText, self.HostelNameText_2)
        mainWindow.setTabOrder(self.HostelNameText_2, self.HostelLocationText)
        mainWindow.setTabOrder(self.HostelLocationText, self.AddHostelButton)
        mainWindow.setTabOrder(self.AddHostelButton, self.HostelIDCombo)
        mainWindow.setTabOrder(self.HostelIDCombo, self.RoomIDText)
        mainWindow.setTabOrder(self.RoomIDText, self.RoomCapacityText)
        mainWindow.setTabOrder(self.RoomCapacityText, self.AddRoomButton)
        mainWindow.setTabOrder(self.AddRoomButton, self.pushButton_2)
        mainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        mainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        mainWindow.setTabOrder(self.pushButton_4, self.pushButton_5)
        mainWindow.setTabOrder(self.pushButton_5, self.pushButton_21)
        mainWindow.setTabOrder(self.pushButton_21, self.StudentNameText)
        mainWindow.setTabOrder(self.StudentNameText, self.pushButton)
        mainWindow.setTabOrder(self.pushButton, self.tabWidget_3)
        mainWindow.setTabOrder(self.tabWidget_3, self.tabWidget)
        mainWindow.setTabOrder(self.tabWidget, self.calendarWidget)
        mainWindow.setTabOrder(self.calendarWidget, self.tabWidget_4)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Kingsway International Montessori & Day Care"))
        self.pushButton_2.setText(_translate("mainWindow", "Home"))
        self.pushButton_3.setText(_translate("mainWindow", "Students"))
        self.pushButton_4.setText(_translate("mainWindow", "Employees"))
        self.pushButton_5.setText(_translate("mainWindow", "Hostels"))
        self.label_2.setText(_translate("mainWindow", "Hostel Management System"))
        self.label.setText(_translate("mainWindow", "Hi ! Kavindu"))
        self.pushButton_21.setText(_translate("mainWindow", "Logout"))
        self.label_6.setText(_translate("mainWindow", "Full Name"))
        self.label_21.setText(_translate("mainWindow", "Category"))
        self.label_22.setText(_translate("mainWindow", "Address"))
        self.label_23.setText(_translate("mainWindow", "Telephone"))
        self.SaveEmployeeButton.setText(_translate("mainWindow", "Save Employee"))
        self.label_10.setText(_translate("mainWindow", "Employee No"))
        self.EmployeeCategoryCombo.setItemText(0, _translate("mainWindow", "Warden"))
        self.EmployeeCategoryCombo.setItemText(1, _translate("mainWindow", "Security"))
        self.EmployeeCategoryCombo.setItemText(2, _translate("mainWindow", "Cleaning"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("mainWindow", "Register Employee"))
        self.label_11.setText(_translate("mainWindow", "Employee No"))
        self.SearchEmployeeButton.setText(_translate("mainWindow", "Search Employee"))
        self.SameAssignmentButton.setText(_translate("mainWindow", "Save Assignment"))
        self.label_12.setText(_translate("mainWindow", "Full Name"))
        self.label_24.setText(_translate("mainWindow", "Assigned Hostel"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("mainWindow", "Assign To Hostel"))
        self.EmployeeTable.setSortingEnabled(False)
        item = self.EmployeeTable.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Emp. ID"))
        item = self.EmployeeTable.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Name"))
        item = self.EmployeeTable.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Category"))
        item = self.EmployeeTable.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Hostel"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("mainWindow", "View All Employees"))
        self.label_5.setText(_translate("mainWindow", "Admission Date"))
        self.label_3.setText(_translate("mainWindow", "Full Name"))
        self.label_7.setText(_translate("mainWindow", "Index No"))
        self.label_15.setText(_translate("mainWindow", "Address"))
        self.label_16.setText(_translate("mainWindow", "Faculty"))
        self.label_18.setText(_translate("mainWindow", "Telephone"))
        self.SaveStudentButton.setText(_translate("mainWindow", "Save Student"))
        self.label_13.setText(_translate("mainWindow", "Hostel Room"))
        self.label_14.setText(_translate("mainWindow", "Hostal Name"))
        self.label_17.setText(_translate("mainWindow", "Batch No"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Register Student"))
        self.label_19.setText(_translate("mainWindow", "Index No"))
        self.label_20.setText(_translate("mainWindow", "Full Name"))
        self.label_25.setText(_translate("mainWindow", "Address"))
        self.label_26.setText(_translate("mainWindow", "Batch No"))
        self.label_27.setText(_translate("mainWindow", "Admission Date"))
        self.label_28.setText(_translate("mainWindow", "Hostel Room"))
        self.label_29.setText(_translate("mainWindow", "Hostal Name"))
        self.label_30.setText(_translate("mainWindow", "Faculty"))
        self.label_31.setText(_translate("mainWindow", "Telephone"))
        self.SearcStudentButton.setText(_translate("mainWindow", "Search Student"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Search Student"))
        self.StudentTable.setSortingEnabled(False)
        item = self.StudentTable.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Index No."))
        item = self.StudentTable.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Name"))
        item = self.StudentTable.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Faculty"))
        item = self.StudentTable.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Room"))
        item = self.StudentTable.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Hostel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainWindow", "View All Students"))
        self.TodayDateLabel.setText(_translate("mainWindow", "2023 JUN 22"))
        self.label_4.setText(_translate("mainWindow", "ATTENDANCE"))
        self.label_8.setText(_translate("mainWindow", "Enter Student Index"))
        self.HostelTable.setSortingEnabled(False)
        item = self.HostelTable.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Hostel. ID"))
        item = self.HostelTable.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Hostel Name"))
        item = self.HostelTable.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Location"))
        item = self.HostelTable.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Rooms"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("mainWindow", "Hostel Details"))
        self.RoomTable.setSortingEnabled(False)
        item = self.RoomTable.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Room ID"))
        item = self.RoomTable.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Capacity"))
        self.SearchHostelButton.setText(_translate("mainWindow", "Search Hostel"))
        self.label_32.setText(_translate("mainWindow", "Hostel"))
        self.groupBox_4.setTitle(_translate("mainWindow", "Hostel Details"))
        self.label_9.setText(_translate("mainWindow", "Location"))
        self.label_34.setText(_translate("mainWindow", "Hostal Name"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("mainWindow", "Room Details"))
        self.label_35.setText(_translate("mainWindow", "ADD HOSTELS"))
        self.label_38.setText(_translate("mainWindow", "Hostal ID"))
        self.label_37.setText(_translate("mainWindow", "Name"))
        self.AddHostelButton.setText(_translate("mainWindow", "ADD"))
        self.label_36.setText(_translate("mainWindow", "Location"))
        self.label_42.setText(_translate("mainWindow", "ADD ROOMS"))
        self.label_39.setText(_translate("mainWindow", "Hostal ID"))
        self.label_40.setText(_translate("mainWindow", "Room ID"))
        self.AddRoomButton.setText(_translate("mainWindow", "ADD"))
        self.label_41.setText(_translate("mainWindow", "Capacity"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("mainWindow", "Customize"))
